// <auto-generated />
using System;
using CareCollar.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareCollar.Persistence.Migrations
{
    [DbContext(typeof(CareCollarDbContext))]
    partial class CareCollarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareCollar.Domain.Entities.CollarDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("BatteryLevel")
                        .HasColumnType("double precision")
                        .HasColumnName("battery_level");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connection");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("serial_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collar_devices");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_collar_devices_pet_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_collar_devices_serial_number");

                    b.ToTable("collar_devices", (string)null);
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.HealthData", b =>
                {
                    b.Property<DateTime>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("CollarId")
                        .HasColumnType("uuid")
                        .HasColumnName("collar_id");

                    b.Property<double?>("ActivityIndex")
                        .HasColumnType("double precision")
                        .HasColumnName("activity_index");

                    b.Property<double>("GpsLatitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("gps_latitude");

                    b.Property<double>("GpsLongitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("double precision")
                        .HasColumnName("gps_longitude");

                    b.Property<double>("HeartRateBPM")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("heart_rate_bpm");

                    b.Property<double>("TemperatureCelsius")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature_celsius");

                    b.HasKey("Time", "CollarId")
                        .HasName("pk_health_data");

                    b.HasIndex("CollarId")
                        .HasDatabaseName("ix_health_data_collar_id");

                    b.HasIndex("Time")
                        .HasDatabaseName("ix_health_data_time");

                    b.ToTable("health_data", (string)null);
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.HealthThreshold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<int>("MetricType")
                        .HasMaxLength(50)
                        .HasColumnType("integer")
                        .HasColumnName("metric_type");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("ThresholdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("threshold_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_health_thresholds");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_health_thresholds_pet_id");

                    b.ToTable("health_thresholds", (string)null);
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Breed")
                        .HasColumnType("text")
                        .HasColumnName("breed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("species");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_pets_user_id");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.CollarDevice", b =>
                {
                    b.HasOne("CareCollar.Domain.Entities.Pet", "Pet")
                        .WithMany("Devices")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_collar_devices_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.HealthData", b =>
                {
                    b.HasOne("CareCollar.Domain.Entities.CollarDevice", "CollarDevice")
                        .WithMany()
                        .HasForeignKey("CollarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_data_collar_devices_collar_id");

                    b.Navigation("CollarDevice");
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.HealthThreshold", b =>
                {
                    b.HasOne("CareCollar.Domain.Entities.Pet", "Pet")
                        .WithMany("Thresholds")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_thresholds_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.Pet", b =>
                {
                    b.HasOne("CareCollar.Domain.Entities.User", "User")
                        .WithMany("Pets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pets_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Thresholds");
                });

            modelBuilder.Entity("CareCollar.Domain.Entities.User", b =>
                {
                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
